### PR TITLE
Support Groups with multiple credentials and logical operators

### PR DESCRIPTION
**Pull request by vplasencia**
## Description

This PR adds support for groups with multiple credentials and logical operators.

## Related Issue

Closes https://github.com/bandada-infra/bandada/issues/223

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

### Information about groups with many credentials

A user can use the Dashboard app or API to create a group with many credentials.

This is the structure of a credential group with only one credential

```bash
{
    (other group info)
    
    ...

    "credentials": "{}"
}

```

Example:

```bash
{
    (other group info)
    
    ...

    "credentials": "{\"id\":\"GITHUB_FOLLOWERS\",\"criteria\":{\"minFollowers\":20}}"
}
```

This is the structure of a credential group with multiple credentials:

```bash
{
    "credentials": "{credentials:[], "expression":[]}"
}

```

Example:

```bash
{
    (other group info)

    ...


    "credentials": "{\"credentials\":[{\"id\":\"BLOCKCHAIN_TRANSACTIONS\",\"criteria\":{\"minTransactions\":12,\"network\":\"Sepolia\"}},{\"id\":\"BLOCKCHAIN_BALANCE\",\"criteria\":{\"minBalance\":\"3\",\"network\":\"Sepolia\"}}],\"expression\":[\"\",\"and\",\"\"]}"
}
```

The user will be able to join a credential group by using a URL like this:

```bash
<dashboard-url>/credentials?group=<group-id>&member=<member-id>&type=multiple
```

Example:

```bash
http://localhost:3001/credentials?group=79609564395766533586300841856737&member=15316025723065452012129624296669307962292967176408402265701167251062457738490&type=multiple
```

Then the user will be asked to prove all the credentials.

Since checking credentials require using different URLs under the hood, the main user data to later check the credentials will be saved in local storage. It's removed when all the values are completed.

The local storage will look like this:

```bash
bandada_credentials: {
    "provider1": [],
    "provider2": [],
    "provider3": [] 
}
```

Example:

```bash
bandada_credentials: {
    "blockchain": ["<oauth-state>",null,"<account-address>"],
    "github": ["<oauth-state>", <oauth-code>],
    "twitter": ["<oauth-state>", <oauth-code>]
}
```

### Some information about the implementation

- Related to evaluating a logical expression.

The expression property, in the credentials' property in a multiple credential group, is an array with strings. Every position will have an empty string or a string with a logical operator. Every empty string represents a credential. Then the first empty string represents the first credential in the list of credentials, the second empty string represents the second credential in the list of credentials and so on. 

If for example, we have something like:

```bash
{
    "credentials": "{credentials:[credential1, credential2], "expression":["", "and", ""]}"
}

```

The expression that will be evaluated is: `credential1 and credential2`.

After all the credentials are evaluated, we will have true or false for every one of them and then we will have an expression like: `["true", "and", "true"]` in case credential1 and credential2 both evaluate to true. 

Then the logical expression will be evaluated using the `Shunting Yard` algorithm adapted to evaluate expressions with logical operators.

- There is a new function to evaluate many credentials in the Credentials library.

### CODE REVIEW

**Review by 0xjei — APPROVED** [review]
Brilliant work! It's really tidy <3

Just a thought: we should open a PR to add more tests to cover more edge cases (like using parenthesis, large numbers of credentials, and so on). Otherwise, it looks great!

**Comment by vplasencia** [comment]
Hey @0xjei thank you very much for reviewing it. I will add a couple of new test cases.

**Comment by vplasencia** [comment]
Hey @0xjei. I just added more tests to cover all possible logical operators and more complex logical expressions, and some of them with parentheses. Added a new test for many credentials with parentheses in the expression. Please see https://github.com/bandada-infra/bandada/pull/530/commits/74e7874bbb9c565fcee6095d6dc9159755bcb9b9.

**Review by 0xjei — APPROVED** [review]
amazing, tysm for adding these cases!

**Pull request merged**
