### PR TITLE
Refactor/remove goerili group

### LINKED ISSUE #518: Remove Goerli groups section
## Description

In this PR https://github.com/bandada-infra/bandada/pull/431 Sepolia was added as the default network but this PR also added a section to display the Goerli groups. 

The idea is to remove the section of the Goerli groups.

### PR DESCRIPTION
**Pull request by Dozie2001**
## Description
Removes Goerili group Component and corresponding Calls

## Related Issue

Closes #518 

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other information

The temporary Goerli group component was removed and the function calls were also removed

### CODE REVIEW

**Comment by vplasencia** [comment]
Hey @Dozie2001 can you use the main branch as a base branch for the PR? Because there is an issue with the dev branch right now that we will solve very soon.

**Comment by Dozie2001** [comment]
Hey @vplasencia  Just saw this. I noticed I kept seeing commits from others contributors. Sorry, kept switching

**Comment by vplasencia** [comment]
Everything is fine now @Dozie2001. Thank you.

**Review by vplasencia — APPROVED** [review]
Looks great. Thank you very much 🙏

**Pull request merged**
