### PR TITLE
fix(dashboard): resolve issue preventing dashboard app from loading

### PR DESCRIPTION
**Pull request by baumstern**
## Description

In the production build, there's an issue preventing the Dashboard app from loading in the browser. The following errors are logged:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'decode')
    at Object.decode (index-CtFWE_9U.js:1659:103201)
    at _ (index-CtFWE_9U.js:1663:5200)
    at pg.decode (index-CtFWE_9U.js:1663:5379)
    at new kQe (index-CtFWE_9U.js:2270:189)
    at UI.generateApi (index-CtFWE_9U.js:2410:41)
    at index-CtFWE_9U.js:2410:288
```

The issue has been traced to UI.generateApi(), which is part of the siwe package. The siwe package was updated from version `^1.1.6` to `^2.1.4` in commit 871f01a. Bumping `siwe` to version `^2.3.2` resolves the current issue.

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by vplasencia** [comment]
Hey @baumstern thank you very much for creating this PR. Is Bandada working fine for you in dev environment? I just tested it and I see some errors in the browser console. 

I think this could help:

https://github.com/spruceid/siwe/issues/165

https://github.com/spruceid/siwe/issues/154

**Comment by baumstern** [comment]
> Hey @baumstern thank you very much for creating this PR. Is Bandada working fine for you in dev environment? I just tested it and I see some errors in the browser console.
> 
> I think this could help:
> 
> [spruceid/siwe#165](https://github.com/spruceid/siwe/issues/165)
> 
> [spruceid/siwe#154](https://github.com/spruceid/siwe/issues/154)

I bumped `siwe` to `^2.3.2` to include the fix mentioned in this comment: https://github.com/spruceid/siwe/issues/165#issuecomment-1686341772.

Just in case, you might need to provide the VITE_PROJECT_ID environment variable to prevent an issue related to wallet connect like following console errors:
Screenshot 2024-05-24 at 23 16 56

**Review by 0xjei — APPROVED** [review]
lovely - tysm!

**Comment by baumstern** [comment]
update: bumped the version of `siwe` from `bandada-api` package as well.

Also, currently we are troubleshooting the issue that this PR introduced with @vplasencia. Signed-in status doesn't persist from her side. But I failed to reproduce it.

**Comment by 0xjei** [comment]
> update: bumped the version of `siwe` from `bandada-api` package as well.
> 
> Also, currently we are troubleshooting the issue that this PR introduced with @vplasencia. Signed-in status doesn't persist from her side. But I failed to reproduce it.

thx for the updates - keep us posted.

**Comment by vplasencia** [comment]
Hey @baumstern!

I will close this PR because there is a new branch that will serve as a reference for future updates of the ethers dependency. Please see https://github.com/bandada-infra/bandada/tree/chore/update-ethers

There is also a new issue focused on improving the wallet UX, please see: https://github.com/bandada-infra/bandada/issues/550

Thank you very much for the work 🙏

**Pull request closed without merging**
